version: "3"

networks:
  nginx_network:
    external: true

services:
  wg:
    build: .
    container_name: wgui
    networks:
      - nginx_network
    cap_add:
      - NET_ADMIN
    environment:
      - SESSION_SECRET
      - WGUI_USERNAME
      - WGUI_PASSWORD
      - WGUI_ENDPOINT_ADDRESS
      - WGUI_PERSISTENT_KEEPALIVE
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
